[package]
name = "csg"
version = "0.1.0"
authors = ["Danilo Guanabara <danguafer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stl_io = "0.6.0"
gpu = { path = "crates/gpu" }
nalgebra = "0.24.0"